owner: kulpacloud
repo: kulpa-status-page

sites:
  - name: Web app
    url: https://app.kulpacloud.com
  - name: Police Command & Control
    url: https://police.kulpacloud.com
  - name: Core API
    url: https://api.kulpa.io/core
    expectedStatusCodes:
      - 200
      - 404

status-website:
  cname: health.kulpacloud.com
  logoUrl: https://raw.githubusercontent.com/kulpacloud/kulpa-status-page/master/assets/Kulpa-logo.png
  name: Kulpa Health

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
